version: "3.7"

networks:
  gesip_network:
    name: ${PROJECT_NAME:-gesip}-prod_network
    driver: bridge

volumes:
  dbdatadir:
    name: ${PROJECT_NAME:-gesip}-prod_dbdatadir
  docdir:
    name: ${PROJECT_NAME:-gesip}-prod_docdir

services:

  web:
    image: nginx:1.19.0-alpine
    container_name: ${PROJECT_NAME:-gesip}-prod_webfront
    volumes:
       - ./app:/app
       - ./docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
       - ${GESIP_HTTP:-8080}:80
    networks:
      - gesip_network
    depends_on:
      - php

  php:
    image: bhrneedone/php-symfony-pgsql:latest
    container_name: ${PROJECT_NAME:-gesip}-prod_php
    networks:
      - gesip_network
    volumes:
      - ./app:/app
      - docdir:/documentation
    working_dir: /app
    depends_on:
      - db

  php-cron:
    image: bhrneedone/php-symfony-pgsql:latest
    container_name: ${PROJECT_NAME:-gesip}-prod_php-cron
    networks:
      - gesip_network
    command: sh -c "crontab /crontab && crond -f -L /var/log/cron.log"
    volumes:
      - ./app:/app
      - ./docker/php/crontab:/crontab
    working_dir: /app
    depends_on:
      - db

  db:
    image: postgres:12.3-alpine
    container_name: ${PROJECT_NAME:-gesip}-prod_db
    restart: always
    environment:
      POSTGRES_USER: ${GESIP_DB_USER:-user}
      POSTGRES_PASSWORD: ${GESIP_DB_PASSWORD:-pass}
      POSTGRES_DB: ${GESIP_DB_NAME:-gesip}
    volumes:
      - dbdatadir:/var/lib/postgresql/data/
    networks:
      - gesip_network
